# fly.toml app configuration file generated for heywoodlh-uptime-kuma on 2026-01-20T17:43:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heywoodlh-uptime-kuma'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'kuma_data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
