# fly.toml app configuration file generated for heywoodlh-cloudflared on 2026-01-20T18:30:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heywoodlh-cloudflared'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
